const players = [
  {
    name: "Csonka Ádám",
    img: "/images/team/adam.png",
    position: "Védő",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 4 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Vértesaljai Ágoston",
    img: "/images/team/agoston-transparent.png",
    position: "Játékos-edző",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 4 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Molnár Bálint",
    img: "/images/team/balint.png",
    position: "Csatár",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 4 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Takács Bence",
    img: "/images/team/bence-transparent.png",
    position: "Középpályás",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Bognár Gyula",
    img: "/images/team/gyula-transparent.png",
    position: "Középpályás",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Tóth János",
    img: "/images/team/jancsi-transparent.png",
    position: "Csatár",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Juronits Krisztián",
    img: "/images/team/juro-transparent.png",
    position: "Kapus",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Kiss Levente",
    img: "/images/team/levi.png",
    position: "Középpályás",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Sárközi Gábor",
    img: "/images/team/gabi-transparent.png",
    position: "Középpályás",
    stats: [
      { label: "Mérkőzés", value: 17 },
      { label: "Győzelem", value: 9 },
      { label: "Vereség", value: 2 },
      { label: "Gól", value: 2 },
      { label: "Gólpassz", value: 2 },
    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzpontosság", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
];

export default players