const players = [
  {
    name: "Csonka Ádám",
    img: "/images/team/adam.png",
    position: "Védő",
    id: 3,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 2 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 2 },
      { label: "Passzolás", value: 3 },
      { label: "Cselezés", value: 2 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Vértesaljai Ágoston",
    img: "/images/team/agoston-transparent01.png",
    position: "Játékos-edző",
    id: 4,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Taktikai felkészültség", value: 3 },
      { label: "Motiváció menedzsment", value: 5 },
      { label: "Krízismenedzsment", value: 4 },
      { label: "Keretkezelési diplomácia", value: 3 },
      { label: "Öltözőpszichológia", value: 5 },
      { label: "Filozófia", value: 5 },
    ],
  },
  {
    name: "Molnár Bálint",
    img: "/images/team/balint.png",
    position: "Csatár",
    id: 5,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 3 },
      { label: "Gyorsaság", value: 3 },
      { label: "Passzolás", value: 4 },
      { label: "Cselezés", value: 2 },
      { label: "Állóképesség", value: 3 },
    ],
  },
  {
    name: "Takács Bence",
    img: "/images/team/bence-transparent.png",
    position: "Középpályás",
    id: 9,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 3 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzolás", value: 5 },
      { label: "Cselezés", value: 2 },
      { label: "Állóképesség", value: 5 },
    ],
  },
  {
    name: "Bognár Gyula",
    img: "/images/team/gyula-transparent.png",
    position: "Középpályás",
    id: 6,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzolás", value: 5 },
      { label: "Cselezés", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Tóth János",
    img: "/images/team/jancsi-transparent.png",
    position: "Csatár",
    id: 2,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 3 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzolás", value: 3 },
      { label: "Cselezés", value: 2 },
      { label: "Állóképesség", value: 2 },
    ],
  },
  {
    name: "Juronits Krisztián",
    img: "/images/team/juro-transparent01.png",
    position: "Kapus",
    id: 8,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzolás", value: 5 },
      { label: "Cselezés", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Kiss Levente",
    img: "/images/team/levi.png",
    position: "Középpályás",
    id: 7,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 5 },
      { label: "Védekezés", value: 4 },
      { label: "Gyorsaság", value: 4 },
      { label: "Passzolás", value: 5 },
      { label: "Cselezés", value: 5 },
      { label: "Állóképesség", value: 4 },
    ],
  },
  {
    name: "Sárközi Gábor",
    img: "/images/team/gabi-transparent.png",
    position: "Középpályás",
    id: 1,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 3 },
      { label: "Gyorsaság", value: 3 },
      { label: "Passzolás", value: 5 },
      { label: "Cselezés", value: 4 },
      { label: "Állóképesség", value: 2 },
    ],
  },
  {
    name: "Tóth Ábel",
    img: "/images/team/abel.png",
    position: "Csatár",
    id: 10,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 4 },
      { label: "Védekezés", value: 3 },
      { label: "Gyorsaság", value: 5 },
      { label: "Passzolás", value: 4 },
      { label: "Cselezés", value: 3 },
      { label: "Állóképesség", value: 4 },
    ],
  },
    {
    name: "Tóth Kornél",
    img: "/images/team/kornel.png",
    position: "Védő",
    id: 11,
    stats: [
      { label: "Mérkőzés", value: 0 },
      { label: "Győzelem", value: 0 },
      { label: "Vereség", value: 0 },
      { label: "Gól", value: 0 },
      { label: "Gólpassz", value: 0 },
      { label: "Döntetlen", value: 0 },

    ],
    skills: [
      { label: "Támadás", value: 3 },
      { label: "Védekezés", value: 5 },
      { label: "Gyorsaság", value: 5 },
      { label: "Passzolás", value: 4 },
      { label: "Cselezés", value: 2 },
      { label: "Állóképesség", value: 5 },
    ],
  },
];

export default players;
